spring.application.name=easy-count

# Hibernate não cria nem altera schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Perfil padrão (caso nenhum seja especificado)
spring.profiles.active=dev
