spring.application.name=easy-count

# Database (assumpt: Postgres local)
spring.datasource.url=jdbc:postgresql://localhost:5432/easy_count_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Use Flyway for schema migrations; disable Hibernate auto-ddl
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Development settings
spring.profiles.active=dev
